name: Node.js PR Edited

on:
  pull_request:
    types:
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci
      - run: npm run test:examples
      - if: ${{ github.event.pull_request.head.repo.fork == false }}
        uses: ArtiomTr/jest-coverage-report-action@v2
      - if: ${{ github.event.pull_request.head.repo.fork == true }}
        run: npm test -- --runInBand

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci
      - run: npm test -- --runInBand
      - run: npm run test:examples
      - run: npm run build
      - run: npm run verify:pack
