name: Node.js PR Open

on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Setup Vals
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
      - run: npm version patch
      - run: |
          git show
          git push
